<?php
/**
 * OldGetFileDtoTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Webpractik\OcfConverter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * tasker
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Webpractik\OcfConverter\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OldGetFileDtoTest Class Doc Comment
 *
 * @category    Class
 * @description OldGetFileDto
 * @package     Webpractik\OcfConverter\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OldGetFileDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OldGetFileDto"
     */
    public function testOldGetFileDto()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cONVERTEDFILE"
     */
    public function testPropertyCONVERTEDFILE()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sTATUS"
     */
    public function testPropertySTATUS()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
