<?php
/**
 * MainOcfApiApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Webpractik\OcfConverter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * tasker
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Webpractik\OcfConverter\Sdk\Test\Api;

use PHPUnit\Framework\TestCase;

/**
 * MainOcfApiApiTest Class Doc Comment
 *
 * @category Class
 * @package  Webpractik\OcfConverter\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MainOcfApiApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Test case for appControllerCheckFileStatus
     * Проверить статус файла, полученного на внешнюю конвертацию.
     */
    public function testAppControllerCheckFileStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerDeleteFile
     * Удалить сконвертированный файл.
     */
    public function testAppControllerDeleteFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerGetJsonApi
     * Получить json ответ.
     */
    public function testAppControllerGetJsonApi()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerGetList
     * Получить список конвертаций.
     */
    public function testAppControllerGetList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for appControllerUploadFile
     * Загрузить файл на конвертацию.
     */
    public function testAppControllerUploadFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
